### ISSUE TITLE
can not run 

### ISSUE THREAD

**Issue by pkingwsd** [realLiangshiwei/Lsw.Abp.AntDesignUI#18]
Microsoft.JSInterop.JSException: Could not find 'AntDesign.interop.domManipulationHelper.addElementTo' ('AntDesign' was undefined).
Error: Could not find 'AntDesign.interop.domManipulationHelper.addElementTo' ('AntDesign' was undefined).
    at https://localhost:44379/global.js?_v=638289244912430522:1:328
    at Array.forEach (<anonymous>)
    at a.findFunction (https://localhost:44379/global.js?_v=638289244912430522:1:296)
    at _ (https://localhost:44379/global.js?_v=638289244912430522:1:2442)
    at https://localhost:44379/global.js?_v=638289244912430522:1:3330
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:44379/global.js?_v=638289244912430522:1:3311)
    at Object.Gt [as invokeJSFromDotNet] (https://localhost:44379/global.js?_v=638289244912430522:1:62537)
    at Object.Ii (https://localhost:44379/_framework/dotnet.7.0.12.qwsz0zk7vs.js:5:71974)
    at _mono_wasm_invoke_js_blazor (https://localhost:44379/_framework/dotnet.7.0.12.qwsz0zk7vs.js:14:103886)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at AntDesign.AntComponentBase.JsInvokeAsync(String code, Object[] args)
   at AntDesign.Dialog.AppendToContainer()
   at AntDesign.Dialog.OnAfterRenderAsync(Boolean isFirst)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
Microsoft.JSInterop.JSException: Could not find 'AntDesign.interop.modalHelper.focusDialog' ('AntDesign' was undefined).
Error: Could not find 'AntDesign.interop.modalHelper.focusDialog' ('AntDesign' was undefined).
    at https://localhost:44379/global.js?_v=638289244912430522:1:328
    at Array.forEach (<anonymous>)
    at a.findFunction (https://localhost:44379/global.js?_v=638289244912430522:1:296)
    at _ (https://localhost:44379/global.js?_v=638289244912430522:1:2442)
    at https://localhost:44379/global.js?_v=638289244912430522:1:3330
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:44379/global.js?_v=638289244912430522:1:3311)
    at Object.Gt [as invokeJSFromDotNet] (https://localhost:44379/global.js?_v=638289244912430522:1:62537)
    at Object.Ii (https://localhost:44379/_framework/dotnet.7.0.12.qwsz0zk7vs.js:5:71974)
    at _mono_wasm_invoke_js_blazor (https://localhost:44379/_framework/dotnet.7.0.12.qwsz0zk7vs.js:14:103886)

**Comment by pkingwsd** [comment]
ABP VNEXT 7.3.3

	  <PackageReference Include="Lsw.Abp.IdentityManagement.Blazor.WebAssembly.AntDesignUI" Version="0.8.0" />
	  <PackageReference Include="Lsw.Abp.SettingManagement.Blazor.WebAssembly.AntDesignUI" Version="0.8.0" />
	  <PackageReference Include="Lsw.Abp.TenantManagement.Blazor.WebAssembly.AntDesignUI" Version="0.8.0" />
	  <PackageReference Include="Lsw.Abp.AspnetCore.Components.WebAssembly.AntDesignTheme" Version="0.8.0" />

**Comment by realLiangshiwei** [comment]
Hi,

Can you upload a test project to github?
